name: Linting

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  lint:
    name: eslint dry run
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true
      - run: npm ci
      - run: npm run lint